### PR TITLE
Add support for HDT belly node managemnent

### PR DESCRIPTION
**Pull request by t3h0th3r**
Suppress belly node scaling while wearing something covering the belly that is not worn on the bodyslot.

### CODE REVIEW

**Comment by MinLL** [comment]
Hey t3h0th3r,

Looks good for the most part! Did you add the magic effect / applicable changes to the quest (Devious Deviants) esp, instead of Integration (The esm) itself though?

**Comment by t3h0th3r** [comment]
I added it to the esp, because i din't know how i could modify the esm (i r n00b).
Little disclaimer, this is more or less 100% rip off of the original breast node management code and also my first papyrus scripts ever (i'm a bit proficient in shell scripting and a little python, though).

**Comment by MinLL** [comment]
No worries! If you can add your changes to the .esm instead of the .esp, I'll merge this for 2.9.1 (Which will be released soon). 

To edit Integration's esm, you need to temporarily convert it to a .esp. Wrye Bash can accomplish this easily. Apply your changes, then convert your newly modified esp back to an esm.

**Comment by t3h0th3r** [comment]
Ok, i'll give it a go. I will have to add the effect/keyword to all applicable devices too...

**Comment by MinLL** [comment]
Great! One more thing: Make sure you're working off of the esm on the Development branch, and not master: It contains changes which have not yet been merged in to master. :)

**Comment by t3h0th3r** [comment]
Thanks for the heads-up :)

**Comment by t3h0th3r** [comment]
Will open a new pr against dev branch.

**Pull request closed without merging**
